### ISSUE TITLE
Stdlib make has bad dependency

### ISSUE THREAD

**Issue by bernecky** [SacBase/Stdlib#18] opened 2018-03-11 19:51 UTC
I just rebuilt Stdlib (make clean; make -j8) and it died, this way:

[ 83%] Generating /home/sac/sac/BASE/Stdlib/build/src-seq/stdio/src/FibreIO/ScanFlt.o for target `seq'
/home/sac/sac/BASE/Stdlib/src/stdio/src/FibreIO/ScanDbl.c:7:27: fatal error: FibreScan.tab.h: No such file or directory

Rerunning with "make" allowed the build to complete normally, so it looks like FibreIO/ScanDbl.c
is missing a dependence on FibreScan.tab.h. I did not try repeating the "make -j8".

git log shows this as latest commit: 24eb85ee488548db0262b8e4b16c610a3de9f50d

**Comment by hv15** [comment] 2020-09-12 15:14
This is a duplicate of #37, am closing this one.

**Closed by hv15** 2020-09-12 15:14 UTC
Labels: bug
